//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairfaxCounty.JCAS_Public_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JcasHoliday
    {
        public int Id { get; set; }
        public string HolidayName { get; set; }
        public System.DateTime HolidayStart { get; set; }
        public int YearRepeat { get; set; }
        public int HolidayMonth { get; set; }
        public Nullable<int> SpecificDay { get; set; }
        public Nullable<int> SpecificWeekday { get; set; }
        public Nullable<int> SpecificWeekdaySequence { get; set; }
        public int SundayMove { get; set; }
        public int SaturdayMove { get; set; }
        public int HolidayDays { get; set; }
        public string UserLoginIdUpdate { get; set; }
        public byte[] RowVersionId { get; set; }
    }
}
