//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairfaxCounty.JCAS_Public_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JcasRule
    {
        public int Id { get; set; }
        public string RuleName { get; set; }
        public string RuleDescription { get; set; }
        public int SessionMonthSequence { get; set; }
        public int SessionFromDateTypeId { get; set; }
        public int SessionFromSequence { get; set; }
        public int SessionToDateTypeId { get; set; }
        public int SessionToSequence { get; set; }
        public int HearingTypeCount { get; set; }
        public string UserGroup { get; set; }
        public string UserLoginIdUpdate { get; set; }
        public byte[] RowVersionId { get; set; }
        public int SubmitFromDateTypeId { get; set; }
        public int SubmitFromSequence { get; set; }
        public int SubmitToDateTypeId { get; set; }
        public int SubmitToSequence { get; set; }
    
        public virtual JcasDateType JcasSessionFromDateType { get; set; }
        public virtual JcasDateType JcasSessionToDateType { get; set; }
        public virtual JcasDateType JcasSubmitToDateType { get; set; }
        public virtual JcasDateType JcasSubmitFromDateType { get; set; }
    }
}
