//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairfaxCounty.JCAS_Public_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JcasSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JcasSession()
        {
            this.JcasSessionRequests = new HashSet<JcasSessionRequest>();
        }
    
        public int Id { get; set; }
        public System.DateTime SessionDate { get; set; }
        public Nullable<int> AttorneyId { get; set; }
        public int HearingTypeId { get; set; }
        public Nullable<int> CourtroomId { get; set; }
        public string UserLoginIdUpdate { get; set; }
        public byte[] RowVersionId { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
    
        public virtual JcasAttorney JcasAttorney { get; set; }
        public virtual JcasCourtroom JcasCourtroom { get; set; }
        public virtual JcasHearingType JcasHearingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JcasSessionRequest> JcasSessionRequests { get; set; }
    }
}
