//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairfaxCounty.JCAS_Public_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JcasAttorney
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JcasAttorney()
        {
            this.JcasAttorneyHearingTypes = new HashSet<JcasAttorneyHearingType>();
            this.JcasSessions = new HashSet<JcasSession>();
        }
    
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string BarNumber { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
        public byte[] Password { get; set; }
        public Nullable<System.DateTime> PasswordExpires { get; set; }
        public int FailedLoginAttempts { get; set; }
        public Nullable<System.DateTime> LastPasswordChange { get; set; }
        public bool EmailIsConfirmed { get; set; }
        public byte[] EmailConfirmationCode { get; set; }
        public Nullable<System.DateTime> EmailConfirmationExpires { get; set; }
        public string FullName { get; set; }
        public string UserLoginIdUpdate { get; set; }
        public byte[] RowVersionId { get; set; }
        public string LawFirmName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JcasAttorneyHearingType> JcasAttorneyHearingTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JcasSession> JcasSessions { get; set; }
    }
}
