//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairfaxCounty.JCAS_Public_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JcasSessionRequest
    {
        public int Id { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> AttorneyId { get; set; }
        public Nullable<int> CourtroomId { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public string UserLoginIdUpdate { get; set; }
        public byte[] RowVersionId { get; set; }
    
        public virtual JcasSession JcasSession { get; set; }
    }
}
